### ISSUE TITLE
Can't Install model

### ISSUE THREAD

**Issue by sam1am** [withcatai/catai#5] opened 2023-04-27 16:29 UTC
I tried this on the 22nd and was able to install models but not get it to serve (it complains model not found). 

With the latest version it doesn't appear to be installing models anymore. 

```
catai install Vicuna-13B
$ cd /usr/lib/node_modules/catai
```

When I run install I just see a cd command echo'd out to the terminal and nothing else. Same thing if I try to run it from that directory.

**Comment by sam1am** [comment] 2023-04-27 16:50
I tried this in Windows as well and got the same result.

**Comment by ido-pluto** [comment] 2023-04-27 17:09
Thank you for reporting, I am facing the same issue - I am on that :)

**Comment by ido-pluto** [comment] 2023-04-27 17:14
The problem is the URL of the model change, for the meantime, you can install the model directory from a link:
```bash
catai install https://huggingface.co/eachadea/ggml-vicuna-13b-1.1/resolve/main/ggml-vic13b-q4_0.bin
```

**Comment by mledwards** [comment] 2023-05-30 09:19
![image](https://github.com/ido-pluto/catai/assets/2692615/add1f805-354a-47ee-b914-134a94638c94)

I tried that install line, and got this one when serving

**Comment by ido-pluto** [comment] 2023-05-30 10:27
I know there is a bug with installing by version.
I will look into that

**Comment by mledwards** [comment] 2023-05-30 10:34
Thank you. I really appreciate the work you're putting in here. This sort of library helps simplify the crazy world of open source LLMs.

**Comment by ido-pluto** [comment] 2023-05-30 16:36
The problem is a new GGML format that is not yet supported by llama.cpp, for now, you can try the old format:

```
https://huggingface.co/eachadea/ggml-vicuna-13b-1.1/resolve/819b698c54b906ca7f3e1774cf748c2018932b07/ggml-vic13b-uncensored-q4_0.bin
```

**Comment by ido-pluto** [comment] 2023-05-31 11:42
The model links are now updated, so this issue should be fixed until llama.cpp can handle ggml v3.

**Comment by mledwards** [comment] 2023-05-31 13:07
Works for me! Thank you sir.

**Closed as completed** 2023-05-31 13:08 UTC
